# Generated by Django 4.2.3 on 2023-08-15 07:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("phone", models.CharField(max_length=10)),
                ("question", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
