# Generated by Django 4.2.3 on 2023-08-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutionapp", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.CharField(max_length=6),
        ),
    ]
