# Generated by Django 4.2.3 on 2023-08-15 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("solutionapp", "0003_alter_feedback_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=45)),
                ("user_pass", models.CharField(max_length=45)),
                ("name", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
