# Generated by Django 4.2.3 on 2023-08-15 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("solutionapp", "0004_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offers_Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_contents", models.CharField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
