# Generated by Django 4.2.3 on 2023-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solutionapp", "0005_offers_scheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee_Type",
            fields=[
                (
                    "employee_type",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("charge_permonth", models.CharField(max_length=20)),
                ("other_details", models.TextField()),
            ],
        ),
    ]
