# Generated by Django 4.2.3 on 2023-08-15 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("solutionapp", "0006_employee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_type",
            name="charge_permonth",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=45)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                ("experience", models.CharField(max_length=20)),
                (
                    "employee_pic",
                    models.FileField(default="", upload_to="solutionapp/employee_pic"),
                ),
                ("about_employee", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "employee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="solutionapp.employee_type",
                    ),
                ),
            ],
        ),
    ]
